INSERT INTO bikes (user_id, title, description, image_url, price, category, discipline) 
Values
(ID,"Cervelo S3")
(ID,'Giant TCR Advanced 0 disc',)
(ID,'Cervelo S5',)
(ID,'Specialized S-Works Venge',)
(ID,'Cannondale SystemSix',)
(ID,'Kona Hei Hei',)
(ID,'Giant Trance',)
(ID,'Canyon Grail',)
(ID,'Specialized Tarmac',)
(ID,'BMC TimeMachine',)
(ID,'Factor 02',)
(ID,'Santa Cruz V10',)
(ID,'Ridley Noah Fast',)
(ID,'Trek Domane',)
(ID,'Kona Rove',)
(ID,'Canyon Ultimate',)
(ID,'Cannondale CAAD 13',)
(ID,'Norco Optic C1',)
(ID,'Wilier Zero SLR',)
(ID,'Factor Vista',)
(ID,'Pinerello Dogma F12',)
(ID,'Trek Madone',)
(ID,'LIV avail Pro ',)
(ID,'Colnago C64',)
(ID,'Kona Roadhouse',)
(ID,'Trek Emonda',)
(ID,'Cervelo P5',)
(ID,'Canyon Aeroad CF SLX',)
(ID,'Trek Supercaliber',)
(ID,'Kona Process 134',)
(ID,'',)
(ID,'',)
(ID,'Specialized S-Works Shiv Disc',)
(ID,'',)
(ID,'OPEN WI.DE',)
(ID,'',)
(ID,'Trek Topfuel',)
(ID,'Cannondale Topstone',)
(ID,'Bianchi Oltre',)
(ID,'Kona Honzo',)
(ID,'Cervelo P5X',)
(ID,'3T Exploro',)
(ID,'Otso Warkin',)
(ID,'Kona Libre DL',)
(ID,'Canyon Speedmax',)
(ID,'',)
(ID,'Specialized Stuntjumped',)
(ID,'3T Strada',)
(ID,'',)
(ID,'',)
(ID,'',)