INSERT INTO bikes (user_id, title, description, image_url, price, category, discipline, featured) 
Values
(ID,"Cervelo S3", "Ultra fast, mid-range Aero Bike")
(ID,'Giant TCR Advanced 0 disc',"Climber's dream bike, great value")
(ID,'Cervelo S5', "World Tour quality, uncompromising speed")
(ID,'Specialized S-Works Venge',"Everyone's Dream Bike")
(ID,'Cannondale SystemSix',"Fast bike, sleek look.")
(ID,'Kona Hei Hei',"Race this bike to podiums")
(ID,'Giant Trance',"Perfect XC into bike")
(ID,'Canyon Grail',"Fun anywhere, looks sily")
(ID,'Specialized Tarmac',"ride the roads without feeling them")
(ID,'BMC TimeMachine',"Spend the money to look the part")
(ID,'Factor 02',"Limited bike, perfect if you live near big mountains")
(ID,'Santa Cruz V10',"Creme-de-la-creme of mountain bikes")
(ID,'Ridley Noah Fast',"The name says it all")
(ID,'Trek Domane',"all-road, not all budget")
(ID,'Kona Rove',"entry level road and do-it-all bike")
(ID,'Canyon Ultimate',"Beautiful piece of German engineering")
(ID,'Cannondale CAAD 13',"Aluminium machine, perfect for road crits")
(ID,'Norco Optic C1',"The Canadian take on enduro perfection")
(ID,'Wilier Zero SLR',"gorgeous, effective, and gorgeous")
(ID,'Factor Vista',"unlimited ")
(ID,'Pinerello Dogma F12',)
(ID,'Trek Madone',)
(ID,'LIV avail Pro ',)
(ID,'Colnago C64',)
(ID,'Kona Roadhouse',)
(ID,'Trek Emonda',)
(ID,'Cervelo P5',)
(ID,'Canyon Aeroad CF SLX',)
(ID,'Trek Supercaliber',)
(ID,'Kona Process 134',)
(ID,'Felt AR advanced',)
(ID,'BMC teamelite 01 ONE',)
(ID,'Specialized S-Works Shiv Disc',)
(ID,'Norco Section XR  C',)
(ID,'OPEN WI.DE',)
(ID,'Scott Addict',)
(ID,'Trek Topfuel',)
(ID,'Cannondale Topstone',)
(ID,'Bianchi Oltre',)
(ID,'Kona Honzo',)
(ID,'Cervelo P5X',)
(ID,'3T Exploro',)
(ID,'Otso Warkin',)
(ID,'Kona Libre DL',)
(ID,'Canyon Speedmax',)
(ID,'Scott Scale',)
(ID,'Specialized Stuntjumped',)
(ID,'3T Strada',)
(ID,'Merida Reacto Disc',)
(ID,'Norco Search XR Carbon',)
(ID,'De Rosa SK Disc',)